# Numpy

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
pip install --upgrade numpy

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------------- -------------------------- 20.5/60.9 kB ? eta -:--:--
     ------------- -------------------------- 20.5/60.9 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.9 kB 217.9 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.9 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 231.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.5 MB 825.8 kB/s eta 0:00:20
   ---------------------------------------- 0.1/16.5 MB 880.9 kB/s eta 0:00:19
   -----------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
astropy 5.3.4 requires numpy<2,>=1.21, but you have numpy 2.0.0 which is incompatible.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.0.0 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.0.0 which is incompatible.
numba 0.59.0 requires numpy<1.27,>=1.22, but you have numpy 2.0.0 which is incompatible.
pandas 2.1.4 requires numpy<2,>=1.23.2; python_version == "3.11", but you have numpy 2.0.0 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.0.0 which is incompatible.
scipy 1.11.4 requires numpy<1.28.0,>=1.21.6, but you have numpy 2.0.0 which is inc

In [7]:
l = [45, "sam", 2.5, 36, 77, 88, 99, 100]
import numpy as np
ar = np.array(l)
print(ar,type(ar))

['45' 'sam' '2.5' '36' '77' '88' '99' '100'] <class 'numpy.ndarray'>


In [10]:
l1 = [78, 88, 98, 45, 64, 56, 12, 11, 31, 23, 10, 30, 25, 24, 23]
print(l,type(l))

[45, 'sam', 2.5, 36, 77, 88, 99, 100] <class 'list'>


In [11]:
ar = np.array(l1)
print(ar,type(ar))

[78 88 98 45 64 56 12 11 31 23 10 30 25 24 23] <class 'numpy.ndarray'>


In [12]:
ar.ndim

1

In [13]:
ar.shape

(15,)

In [14]:
ar.size

15

In [16]:
len(ar)

15

In [17]:
ar.dtype

dtype('int32')

In [18]:
ar = np.array([l1])
print(ar,type(ar))

[[78 88 98 45 64 56 12 11 31 23 10 30 25 24 23]] <class 'numpy.ndarray'>


In [19]:
ar.ndim

2

In [20]:
ar.shape

(1, 15)

In [21]:
ar.size

15

In [23]:
len(ar)

1

In [24]:
ar.dtype

dtype('int32')

In [28]:
ar = np.array([l1],ndmin=3)
print(ar,type(ar))

[[[78 88 98 45 64 56 12 11 31 23 10 30 25 24 23]]] <class 'numpy.ndarray'>


In [29]:
ar.ndim

3

In [30]:
ar.shape

(1, 1, 15)

In [31]:
ar.size

15

In [32]:
len(ar)

1

In [33]:
ar.dtype

dtype('int32')

In [34]:
ar = np.array([l1],dtype="f")
print(ar,type(ar))

[[78. 88. 98. 45. 64. 56. 12. 11. 31. 23. 10. 30. 25. 24. 23.]] <class 'numpy.ndarray'>


In [35]:
ar = np.array([l1],dtype=float)
print(ar,type(ar))

[[78. 88. 98. 45. 64. 56. 12. 11. 31. 23. 10. 30. 25. 24. 23.]] <class 'numpy.ndarray'>


In [36]:
ar = np.array([l1],np.float_)
print(ar,type(ar))

[[78. 88. 98. 45. 64. 56. 12. 11. 31. 23. 10. 30. 25. 24. 23.]] <class 'numpy.ndarray'>


In [37]:
ar = np.array([l1],dtype=np.float64)
print(ar,type(ar))

[[78. 88. 98. 45. 64. 56. 12. 11. 31. 23. 10. 30. 25. 24. 23.]] <class 'numpy.ndarray'>


In [39]:
ar = np.array([l1])
print(ar,type(ar))

[[78 88 98 45 64 56 12 11 31 23 10 30 25 24 23]] <class 'numpy.ndarray'>


In [40]:
ar=np.float_(ar)
ar

array([[78., 88., 98., 45., 64., 56., 12., 11., 31., 23., 10., 30., 25.,
        24., 23.]])

In [41]:
ar = ar.astype(float)
ar

array([[78., 88., 98., 45., 64., 56., 12., 11., 31., 23., 10., 30., 25.,
        24., 23.]])

In [42]:
ar.dtype

dtype('float64')

In [43]:
ar=np.array([l1])
print(ar,type(ar))

[[78 88 98 45 64 56 12 11 31 23 10 30 25 24 23]] <class 'numpy.ndarray'>


In [44]:
ar.shape

(1, 15)

In [47]:
ar.shape=(5,3)
ar

array([[78, 88, 98],
       [45, 64, 56],
       [12, 11, 31],
       [23, 10, 30],
       [25, 24, 23]])

In [48]:
ar.reshape(3,5)

array([[78, 88, 98, 45, 64],
       [56, 12, 11, 31, 23],
       [10, 30, 25, 24, 23]])

In [49]:
ar

array([[78, 88, 98],
       [45, 64, 56],
       [12, 11, 31],
       [23, 10, 30],
       [25, 24, 23]])

In [50]:
ar = ar.reshape(3,5)
ar

array([[78, 88, 98, 45, 64],
       [56, 12, 11, 31, 23],
       [10, 30, 25, 24, 23]])

In [51]:
ar.size

15

In [52]:
len(ar)

3

In [53]:
t = {4, 5, 7, 8, 9, 10, 11, 12}
ar = np.array([t])
print(ar,type(ar))

[{4, 5, 7, 8, 9, 10, 11, 12}] <class 'numpy.ndarray'>


In [54]:
ar.ndim

1

In [55]:
ar.shape

(1,)

In [56]:
ar.shape

(1,)

In [57]:
ar.size

1

In [58]:
len(ar)

1

In [59]:
ar.dtype

dtype('O')

In [60]:
%timeit [i**2 for i in range(1,10)]

933 ns ± 4.59 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [61]:
%timeit np.arange(1,10)**2

1.5 µs ± 5.17 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [63]:
ar = np.zeros(4)
ar

array([0., 0., 0., 0.])

In [64]:
ar = np.zeros(4,dtype=int)
ar

array([0, 0, 0, 0])

In [65]:
ar = np.zeros((3,4),dtype=int)
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [66]:
ar = np.ones(4)
ar

array([1., 1., 1., 1.])

In [67]:
ar = np.ones(4,dtype=int)
ar

array([1, 1, 1, 1])

In [68]:
ar = np.ones((3,4),dtype=int)
ar

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [69]:
ar=np.empty(5)
ar

array([0.00000000e+000, 6.95323242e-310, 4.94065646e-324,             nan,
       8.68719193e-312])

In [70]:
ar=np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [71]:
ar=np.arange(2,15,2)
ar

array([ 2,  4,  6,  8, 10, 12, 14])

In [72]:
ar=np.eye(5)
ar

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
ar = np.eye(2,3,dtype=int)
ar

array([[1, 0, 0],
       [0, 1, 0]])

In [74]:
ar=np.linspace(0,20,5)
ar

array([ 0.,  5., 10., 15., 20.])

In [75]:
ar = np.logspace(0,20,5)
ar

array([1.e+00, 1.e+05, 1.e+10, 1.e+15, 1.e+20])

# Day2

In [77]:
# Random Function

import numpy as np
ar = np.random.rand(5)
print(ar,type(ar))

[0.19300245 0.10458934 0.30510553 0.37523441 0.60791756] <class 'numpy.ndarray'>


In [78]:
import numpy as np
ar = np.random.rand(5,3)
print(ar,type(ar))

[[0.8120104  0.00795593 0.77735862]
 [0.31374976 0.85760648 0.52272294]
 [0.55666032 0.64172511 0.46952468]
 [0.00448233 0.32379146 0.95881929]
 [0.30766899 0.04195314 0.21049966]] <class 'numpy.ndarray'>


In [79]:
import numpy as np
ar = np.random.randn(5)
print(ar,type(ar))

[-0.30210258  2.15625366  1.83081566 -1.17116074  0.96157608] <class 'numpy.ndarray'>


In [80]:
import numpy as np
ar = np.random.randn(2,3)
print(ar,type(ar))

[[-0.57796713  0.55328418 -0.24173407]
 [ 1.77706674  1.67291122  0.29890478]] <class 'numpy.ndarray'>


In [81]:
import numpy as np
ar = np.random.ranf(5)
print(ar,type(ar))

[0.53820589 0.34648974 0.4849032  0.53460549 0.67901453] <class 'numpy.ndarray'>


In [82]:
import numpy as np
ar = np.random.ranf(5,3)
print(ar,type(ar))

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [83]:
import numpy as np
ar = np.random.ranf((5,3))
print(ar,type(ar))

[[0.75927292 0.00627995 0.73154866]
 [0.63671325 0.33148927 0.37872314]
 [0.61932214 0.56428583 0.9452651 ]
 [0.06454308 0.6633048  0.33383166]
 [0.17731765 0.32255668 0.46046928]] <class 'numpy.ndarray'>


In [84]:
import numpy as np
ar = np.random.randint(5)
print(ar,type(ar))

4 <class 'int'>


In [87]:
import numpy as np
ar = np.random.randint(1,10)
print(ar,type(ar))

8 <class 'int'>


In [86]:
import numpy as np
ar = np.random.randint(1,10,3)
print(ar,type(ar))

[3 6 4] <class 'numpy.ndarray'>


In [88]:
l = [78,89,45,66,12,36,14,55]
import numpy as np
ar = np.array(l)
print(ar)

[78 89 45 66 12 36 14 55]


In [89]:
ar[0:7:3]

array([78, 66, 14])

In [92]:
import numpy as np
ar = np.array([[4,5,6],[7,8,9],[11,21,33]])
print(ar,type(ar))

[[ 4  5  6]
 [ 7  8  9]
 [11 21 33]] <class 'numpy.ndarray'>


In [96]:
ar[0]

array([4, 5, 6])

In [97]:
ar[1]

array([7, 8, 9])

In [98]:
ar[2]

array([11, 21, 33])

In [99]:
ar

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [11, 21, 33]])

In [100]:
ar[0:2,1:3]

array([[5, 6],
       [8, 9]])

In [101]:
ar[0:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [102]:
ar[1:3]

array([[ 7,  8,  9],
       [11, 21, 33]])

In [103]:
ar[1:3,::]

array([[ 7,  8,  9],
       [11, 21, 33]])

In [104]:
ar[1:3,:]

array([[ 7,  8,  9],
       [11, 21, 33]])

In [105]:
ar[1:3,0:3]

array([[ 7,  8,  9],
       [11, 21, 33]])

In [106]:
ar[1:3,-1:-3:-1]

array([[ 9,  8],
       [33, 21]])

In [107]:
ar[1:3,-1:-3]

array([], shape=(2, 0), dtype=int32)

In [108]:
ar[1:3,-1:-3:1]

array([], shape=(2, 0), dtype=int32)

In [109]:
ar

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [11, 21, 33]])

In [110]:
ar[[0,1,0],[0,1,2]]

array([4, 8, 6])

In [111]:
ar[[0,2,0],[0,2,2]]

array([ 4, 33,  6])

In [112]:
ar[[0,2],[1,2]]

array([ 5, 33])

In [113]:
ar[[2,0],[1,2]]

array([21,  6])

In [114]:
ar[[0,2,2,0],[0,0,1,2]]

array([ 4, 11, 21,  6])

In [115]:
ar

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [11, 21, 33]])

In [118]:
ar[0,2]

6

In [119]:
ar[2,0]

11

In [120]:
ar[0,0]

4

In [121]:
ar[1,2]

9

In [122]:
ar[[0,2,2,0],[0,0,1,2]]

array([ 4, 11, 21,  6])

In [123]:
ar[[0,1,2,0],[0,0,1,2]]

array([ 4,  7, 21,  6])

In [124]:
ar[[0,1,2,1],[1,0,1,2]]

array([ 5,  7, 21,  9])

# Day 3

In [1]:
import numpy as np
ar = np.array([4,5,6,78,88,100,3,12,11])
print(ar,type(ar))

[  4   5   6  78  88 100   3  12  11] <class 'numpy.ndarray'>


In [2]:
np.max(ar)

np.int64(100)

In [3]:
np.min(ar)

np.int64(3)

In [4]:
np.sum(ar)

np.int64(307)

In [5]:
max(ar)

np.int64(100)

In [6]:
min(ar)

np.int64(3)

In [7]:
sum(ar)

np.int64(307)

In [8]:
ar1 = np.array([[45,22,66],[77,88,99]])
print(ar1)

[[45 22 66]
 [77 88 99]]


In [9]:
ar1.max(axis=0)

array([77, 88, 99])

In [10]:
ar1.max(axis=1)

array([66, 99])

In [11]:
np.max(ar1)

np.int64(99)

In [13]:
ar1.min(axis=0)

array([45, 22, 66])

In [15]:
ar1.sum(axis=0)

array([122, 110, 165])

In [16]:
ar1.sum(axis=1)

array([133, 264])

In [17]:
np.std(ar1)

np.float64(26.04749934681297)

In [18]:
np.sqrt(ar1)

array([[6.70820393, 4.69041576, 8.1240384 ],
       [8.77496439, 9.38083152, 9.94987437]])

In [19]:
p=np.array([[45,55,66],[77,88,99]])
print(p)

[[45 55 66]
 [77 88 99]]


In [20]:
q=np.array([[12,23,31],[14,25,36]])
print(q)

[[12 23 31]
 [14 25 36]]


In [21]:
p

array([[45, 55, 66],
       [77, 88, 99]])

In [22]:
q

array([[12, 23, 31],
       [14, 25, 36]])

In [24]:
np.hstack((p,q))

array([[45, 55, 66, 12, 23, 31],
       [77, 88, 99, 14, 25, 36]])

In [25]:
h=np.hstack((p,q))
print(h)

[[45 55 66 12 23 31]
 [77 88 99 14 25 36]]


In [26]:
np.vstack((p,q))

array([[45, 55, 66],
       [77, 88, 99],
       [12, 23, 31],
       [14, 25, 36]])

In [27]:
v=np.vstack((p,q))
print(v)

[[45 55 66]
 [77 88 99]
 [12 23 31]
 [14 25 36]]


In [28]:
import numpy as np
l=[4,5,6,7,8,9,10]
a=np.asarray(l)
print(a)

[ 4  5  6  7  8  9 10]


In [29]:
type(a)

numpy.ndarray

In [30]:
import numpy as np
l=[45,55,66,78,88,19]
a=iter(l)
y=np.fromiter(a,dtype=int)
print(y)

[45 55 66 78 88 19]


In [31]:
type(y)

numpy.ndarray

In [32]:
y.dtype

dtype('int64')

In [34]:
import numpy as np
l=[45,55,66,78,88,19]
a=(l)
y=np.array(a,dtype="O")
print(y)

[45 55 66 78 88 19]


In [35]:
y.dtype

dtype('O')

In [36]:
import numpy as np
l=[45,55,66,78,88,99]
y=np.array(l,dtype="S1")
print(y)

[b'4' b'5' b'6' b'7' b'8' b'9']


In [37]:
import numpy as np
l=[45,55,66,78,88,99]
y=np.frombuffer(y,dtype="S1")
print(y)

[b'4' b'5' b'6' b'7' b'8' b'9']


In [39]:
import numpy as np
l=[45,55,66,78,88,99]
mat=np.matrix(l)
mat

matrix([[45, 55, 66, 78, 88, 99]])

In [40]:
import numpy as np
ar=np.array([7,8,9,14,25,36])
print(ar)

[ 7  8  9 14 25 36]


In [41]:
ar[2]

np.int64(9)

In [42]:
ar[-4]

np.int64(9)

In [43]:
ar=np.array([[4,5,6],[7,8,9],[10,11,12]])
print(ar)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [44]:
ar[1]

array([7, 8, 9])

In [45]:
ar[1][1]

np.int64(8)

In [46]:
ar[1,1]

np.int64(8)

In [47]:
import numpy as np
ar=np.array([7,8,9,14,25,36])
print(ar)

[ 7  8  9 14 25 36]


In [48]:
for k in ar:
    print(k)

7
8
9
14
25
36


In [49]:
for k in ar:
    print(k,end=" ")

7 8 9 14 25 36 

In [50]:
ar=np.array([[4,5,6],[7,8,9],[10,11,12]])
print(ar)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [51]:
for k in ar:
    print(k)

[4 5 6]
[7 8 9]
[10 11 12]


In [52]:
for k in ar:
    for a in k:
        print(a,end=" ")

4 5 6 7 8 9 10 11 12 

In [53]:
ar=np.array([[[4,5,6],[7,8,9],[10,11,12]]])
print(ar)

[[[ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [54]:
for k in ar:
    print(k)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
for k in ar:
    for a in k:
        for b in a:
            print(b,end=" ")

4 5 6 7 8 9 10 11 12 

In [56]:
import numpy as np
ar=np.array([7,8,9,14,25,36])
print(ar)

[ 7  8  9 14 25 36]


In [57]:
for k in np.nditer(ar):
    print(k,end=" ")

7 8 9 14 25 36 

In [58]:
ar=np.array([[4,5,6],[7,8,9],[10,11,12]])
print(ar)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [59]:
for k in np.nditer(ar):
    print(k,end=" ")

4 5 6 7 8 9 10 11 12 

In [60]:
ar=np.array([[[4,5,6],[7,8,9],[10,11,12]]])
print(ar)

[[[ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [61]:
for k in np.nditer(ar):
    print(k,end=" ")

4 5 6 7 8 9 10 11 12 

In [62]:
ar=np.array([[4,5,6],[7,8,9],[10,11,12]])
print(ar)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [63]:
at=ar.T
at

array([[ 4,  7, 10],
       [ 5,  8, 11],
       [ 6,  9, 12]])

In [64]:
for k in np.nditer(at):
    print(k,end=" ")

4 5 6 7 8 9 10 11 12 

In [65]:
at

array([[ 4,  7, 10],
       [ 5,  8, 11],
       [ 6,  9, 12]])

In [66]:
b=at.copy(order="C")

In [67]:
b

array([[ 4,  7, 10],
       [ 5,  8, 11],
       [ 6,  9, 12]])

In [68]:
for k in np.nditer(b):
    print(k,end=" ")

4 7 10 5 8 11 6 9 12 

In [69]:
d = at.copy(order="F")

In [70]:
d

array([[ 4,  7, 10],
       [ 5,  8, 11],
       [ 6,  9, 12]])

In [71]:
for k in np.nditer(d):
    print(k,end=" ")

4 5 6 7 8 9 10 11 12 

In [72]:
at

array([[ 4,  7, 10],
       [ 5,  8, 11],
       [ 6,  9, 12]])

In [75]:
for k in np.nditer(at,order="C"):
    print(k,end=" ")

4 7 10 5 8 11 6 9 12 

In [76]:
for k in np.nditer(at,order="c"):
    print(k,end=" ")

4 7 10 5 8 11 6 9 12 

In [77]:
for k in np.nditer(at,order="F"):
    print(k,end=" ")

4 5 6 7 8 9 10 11 12 

In [78]:
at

array([[ 4,  7, 10],
       [ 5,  8, 11],
       [ 6,  9, 12]])

In [79]:
for k in np.nditer(at):
    print(k*2,end=" ")

8 10 12 14 16 18 20 22 24 

In [80]:
at

array([[ 4,  7, 10],
       [ 5,  8, 11],
       [ 6,  9, 12]])

In [81]:
for k in np.nditer(at,op_flags=["readwrite"]):
    k[...]=k*2
    print(k,end=" ")

8 10 12 14 16 18 20 22 24 

In [82]:
at

array([[ 8, 14, 20],
       [10, 16, 22],
       [12, 18, 24]])

In [83]:
at

array([[ 8, 14, 20],
       [10, 16, 22],
       [12, 18, 24]])

In [84]:
for k,j in np.ndenumerate(at):
    print(k,"-->",j)

(0, 0) --> 8
(0, 1) --> 14
(0, 2) --> 20
(1, 0) --> 10
(1, 1) --> 16
(1, 2) --> 22
(2, 0) --> 12
(2, 1) --> 18
(2, 2) --> 24


In [85]:
at

array([[ 8, 14, 20],
       [10, 16, 22],
       [12, 18, 24]])

In [86]:
for i in np.nditer(at,flags=["buffered"],op_dtypes=[int]):
    print(i,end=" ")

8 10 12 14 16 18 20 22 24 

In [87]:
for i in np.nditer(at,flags=["buffered"],op_dtypes=[float]):
    print(i,end=" ")

8.0 10.0 12.0 14.0 16.0 18.0 20.0 22.0 24.0 

In [88]:
for i in np.nditer(at,op_dtypes=[int]):
    print(i,end=" ")

8 10 12 14 16 18 20 22 24 

In [89]:
for i in np.nditer(at,op_dtypes=[float]):
    print(i,end=" ")

TypeError: Iterator operand required copying or buffering, but neither copying nor buffering was enabled

In [90]:
import numpy as np
l=[45,55,66,78,88,19]
a=iter(l)
y=np.fromiter(a,dtype="O")
print(y)

[45 55 66 78 88 19]


In [91]:
a = 10
bin(a)

'0b1010'

In [92]:
import numpy as np

In [93]:
a = np.binary_repr(10)
a

'1010'

In [94]:
a = np.binary_repr(10,7)
a

'0001010'

In [96]:
ar = np.array(45)
a = np.binary_repr(ar)
a

'101101'

In [100]:
a = np.bitwise_and(12,6)
a

np.int32(4)

# Day 4

In [2]:
import numpy as np
ar = np.array([45,55,66,77])
ar1 = np.array([50,60,70,80])
a = np.bitwise_and(ar,ar1)
a

array([32, 52, 66, 64])

In [3]:
ar = np.array([[45,55],[66,77]])
ar1 = np.array([50,60,70,80])
a = np.bitwise_and(ar,ar1)
a

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [4]:
ar = np.array([[45,55],[66,77]])
ar1 = np.array([5,10],[11,20])
a = np.bitwise_and(ar,ar1)
a

TypeError: Field elements must be 2- or 3-tuples, got '11'

In [5]:
ar = np.array([[45,55],[66,77]])
ar1 = np.array([[5,10],[11,20]])
a = np.bitwise_and(ar,ar1)
a

array([[5, 2],
       [2, 4]])

In [6]:
ar

array([[45, 55],
       [66, 77]])

In [7]:
ar1

array([[ 5, 10],
       [11, 20]])

In [8]:
ar = np.array([[[45,55],[66,77]]])
ar1 = np.array([[5,10],[11,20]])
a = np.bitwise_and(ar,ar1)
a

array([[[5, 2],
        [2, 4]]])

In [9]:
ar = np.array([[[45,55],[66,77]]])
ar1 = np.array([[5,10],[11]])
a = np.bitwise_and(ar,ar1)
a

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [10]:
b = np.bitwise_or(45,5)

In [11]:
b

np.int32(45)

In [12]:
ar = np.array([[[45,55],[66,77]]])
ar1 = np.array([[5,10],[11,20]])
a = np.bitwise_or(ar,ar1)
a

array([[[45, 63],
        [75, 93]]])

In [13]:
b = np.bitwise_xor(45,5)

In [14]:
b

np.int32(40)

In [15]:
ar = np.array([[[45,55],[66,77]]])
ar1 = np.array([[5,10],[11,20]])
a = np.bitwise_xor(ar,ar1)
a

array([[[40, 61],
        [73, 89]]])

In [16]:
b = np.bitwise_not(45)

In [17]:
b

np.int64(-46)

In [18]:
ar = np.array([[[45,55],[66,77]]])
ar1 = np.array([[5,10],[11,20]])
a = np.bitwise_not(ar)
a

array([[[-46, -56],
        [-67, -78]]])

In [19]:
b = np.bitwise_not(45,5)

TypeError: return arrays must be of ArrayType

In [21]:
ar = np.array([[45,55],[66,77]])
ar1 = np.array([[5,10],[11,20]])
a = np.bitwise_not(ar,ar1)
a

array([[-46, -56],
       [-67, -78]])

In [22]:
b = np.invert(45)

In [23]:
b

np.int64(-46)

In [24]:
b = np.invert(ar)
b

array([[-46, -56],
       [-67, -78]])

In [25]:
np.binary_repr(45)

'101101'

In [26]:
np.binary_repr(-46)

'-101110'

In [27]:
import numpy as np

In [28]:
a = np.char.add(["My name is ","I am from "],["Puja","Samastipur"])
print(a)

['My name is Puja' 'I am from Samastipur']


In [29]:
a = np.char.multiply("@",3)
print(a)

@@@


In [30]:
a = np.char.multiply("*",3)
print(a)

***


In [31]:
a = np.char.upper("Puja")
print(a)

PUJA


In [32]:
a

array('PUJA', dtype='<U4')

In [33]:
ar = np.array([20,30,60,80,120])
print(ar)

[ 20  30  60  80 120]


In [34]:
print(np.sin(ar*np.pi/180))

[0.34202014 0.5        0.8660254  0.98480775 0.8660254 ]


In [35]:
print(np.cos(ar*np.pi/180))

[ 0.93969262  0.8660254   0.5         0.17364818 -0.5       ]


In [36]:
print(np.tan(ar*np.pi/180))

[ 0.36397023  0.57735027  1.73205081  5.67128182 -1.73205081]


In [37]:
a = np.sin(ar*np.pi/180)
a

array([0.34202014, 0.5       , 0.8660254 , 0.98480775, 0.8660254 ])

In [38]:
cosec = np.arcsin(a)
cosec

array([0.34906585, 0.52359878, 1.04719755, 1.3962634 , 1.04719755])

In [39]:
np.degrees(cosec)

array([20., 30., 60., 80., 60.])

In [40]:
import numpy as np
ar = np.array([11,536,40.505,78.456,30.456,28.101])
ar

array([ 11.   , 536.   ,  40.505,  78.456,  30.456,  28.101])

In [41]:
np.round(ar)

array([ 11., 536.,  41.,  78.,  30.,  28.])

In [42]:
np.around(ar)

array([ 11., 536.,  41.,  78.,  30.,  28.])

In [43]:
np.around(ar,2)

array([ 11.  , 536.  ,  40.51,  78.46,  30.46,  28.1 ])

In [44]:
np.around(ar,-1)

array([ 10., 540.,  40.,  80.,  30.,  30.])

In [45]:
np.floor(ar)

array([ 11., 536.,  40.,  78.,  30.,  28.])

In [46]:
np.ceil(ar)

array([ 11., 536.,  41.,  79.,  31.,  29.])

In [47]:
ar

array([ 11.   , 536.   ,  40.505,  78.456,  30.456,  28.101])

In [48]:
import numpy as np
ar = np.array([[4,5,6],[7,8,9],[11,112,13]])
ar

array([[  4,   5,   6],
       [  7,   8,   9],
       [ 11, 112,  13]])

In [49]:
np.max(ar)

np.int64(112)

In [50]:
np.min(ar)

np.int64(4)

In [51]:
np.max(ar,0)

array([ 11, 112,  13])

In [52]:
np.amax(ar)

np.int64(112)

In [53]:
np.amin(ar)

np.int64(4)

In [54]:
np.amin(ar,axis=0)

array([4, 5, 6])

In [56]:
np.amax(ar,axis=0)

array([ 11, 112,  13])

In [57]:
np.amax(ar,axis=1)

array([  6,   9, 112])

In [58]:
np.amin(ar,axis=1)

array([ 4,  7, 11])

In [60]:
ar

array([[  4,   5,   6],
       [  7,   8,   9],
       [ 11, 112,  13]])

In [61]:
np.average(ar)

np.float64(19.444444444444443)

In [62]:
np.mean(ar)

np.float64(19.444444444444443)

In [63]:
np.average(ar,axis=0)

array([ 7.33333333, 41.66666667,  9.33333333])

In [64]:
np.mean(ar,axis=0)

array([ 7.33333333, 41.66666667,  9.33333333])

In [65]:
np.median(ar)

np.float64(8.0)

In [66]:
ar1 = np.array([[4,5],[11,12]])

In [67]:
np.median(ar1)

np.float64(8.0)

In [69]:
np.std(ar)

np.float64(32.83328633198366)

In [70]:
import numpy as np
ar = np.array([445,55,66,77,88,99,100])
ar

array([445,  55,  66,  77,  88,  99, 100])

In [71]:
ar[0]

np.int64(445)

In [72]:
ar[5]

np.int64(99)

In [73]:
ar[-2]

np.int64(99)

In [74]:
ar=np.array([[4,5],[7,88]])
ar

array([[ 4,  5],
       [ 7, 88]])

In [75]:
ar[0]

array([4, 5])

In [76]:
ar[0][1]

np.int64(5)

In [77]:
ar[0,1]

np.int64(5)

In [78]:
ar[1,1]

np.int64(88)

In [79]:
ar[1][1]

np.int64(88)

In [80]:
ar=np.array([[1,44,66,77],[88,99,100,102],[55,66,77,88]])
ar

array([[  1,  44,  66,  77],
       [ 88,  99, 100, 102],
       [ 55,  66,  77,  88]])

In [81]:
ar[0]

array([ 1, 44, 66, 77])

In [82]:
ar[1]

array([ 88,  99, 100, 102])

In [83]:
ar[2]

array([55, 66, 77, 88])

In [85]:
ar[0,1]

np.int64(44)

In [86]:
ar[0:3]

array([[  1,  44,  66,  77],
       [ 88,  99, 100, 102],
       [ 55,  66,  77,  88]])

In [87]:
ar[0:3,0:4]

array([[  1,  44,  66,  77],
       [ 88,  99, 100, 102],
       [ 55,  66,  77,  88]])

In [88]:
ar[0:3,0:4:2]

array([[  1,  66],
       [ 88, 100],
       [ 55,  77]])

In [89]:
ar[1:3,0:4:3]

array([[ 88, 102],
       [ 55,  88]])

In [90]:
ar[(0,1,2,0),(1,2,1,3)]

array([ 44, 100,  66,  77])

In [91]:
ar[[0,1,2,0],[1,2,1,3]]

array([ 44, 100,  66,  77])

In [92]:
ar

array([[  1,  44,  66,  77],
       [ 88,  99, 100, 102],
       [ 55,  66,  77,  88]])

In [93]:
ar = np.array([78,85,15,2,99,103,3,5,6])
ar

array([ 78,  85,  15,   2,  99, 103,   3,   5,   6])

In [94]:
np.sort(ar)

array([  2,   3,   5,   6,  15,  78,  85,  99, 103])

In [95]:
ar

array([ 78,  85,  15,   2,  99, 103,   3,   5,   6])

In [96]:
np.sort(ar,axis=-1,kind=None,order=None)

array([  2,   3,   5,   6,  15,  78,  85,  99, 103])

In [97]:
np.sort(ar,axis=-1,kind="quicksort",order=None)

array([  2,   3,   5,   6,  15,  78,  85,  99, 103])

In [98]:
ar = np.array([[5,45],[3,100]])
ar

array([[  5,  45],
       [  3, 100]])

In [99]:
np.sort(ar)

array([[  5,  45],
       [  3, 100]])

In [100]:
np.sort(ar,axis=1)

array([[  5,  45],
       [  3, 100]])

In [101]:
np.sort(ar,axis=0)

array([[  3,  45],
       [  5, 100]])

In [102]:
np.sort(ar,axis=None)

array([  3,   5,  45, 100])

In [103]:
dtype = [("name","S10"),("height",float),("age",int)]

In [104]:
values = [("sam",1.81,22),("vibhour",1.75,21),("rohit",1.66,25)]

In [105]:
a = np.array(values,dtype=dtype)
a

array([(b'sam', 1.81, 22), (b'vibhour', 1.75, 21), (b'rohit', 1.66, 25)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [106]:
np.sort(a)

array([(b'rohit', 1.66, 25), (b'sam', 1.81, 22), (b'vibhour', 1.75, 21)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [107]:
np.sort(a,order="height")

array([(b'rohit', 1.66, 25), (b'vibhour', 1.75, 21), (b'sam', 1.81, 22)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [108]:
np.sort(a,order="age")

array([(b'vibhour', 1.75, 21), (b'sam', 1.81, 22), (b'rohit', 1.66, 25)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [109]:
np.sort(a,order="name")

array([(b'rohit', 1.66, 25), (b'sam', 1.81, 22), (b'vibhour', 1.75, 21)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [110]:
ar

array([[  5,  45],
       [  3, 100]])

In [111]:
np.argsort(ar)

array([[0, 1],
       [0, 1]])

In [112]:
ar = np.array([[45,55,66],[77,48,100]])
ar

array([[ 45,  55,  66],
       [ 77,  48, 100]])

In [113]:
np.argsort(ar)

array([[0, 1, 2],
       [1, 0, 2]])

In [114]:
ar

array([[ 45,  55,  66],
       [ 77,  48, 100]])

In [115]:
ar.sort()
ar

array([[ 45,  55,  66],
       [ 48,  77, 100]])

In [116]:
ar = np.array([[45,55,66],[77,48,100]])
ar

array([[ 45,  55,  66],
       [ 77,  48, 100]])

In [117]:
np.sort(ar)

array([[ 45,  55,  66],
       [ 48,  77, 100]])

In [118]:
ar

array([[ 45,  55,  66],
       [ 77,  48, 100]])

In [119]:
ar.sort()

In [120]:
ar

array([[ 45,  55,  66],
       [ 48,  77, 100]])

In [121]:
import numpy as np
a = np.array([78,88,99,44])
b = np.array([5,6,7,8])

In [122]:
a

array([78, 88, 99, 44])

In [123]:
b

array([5, 6, 7, 8])

In [124]:
np.concatenate((a,b))

array([78, 88, 99, 44,  5,  6,  7,  8])

In [125]:
np.stack((a,b))

array([[78, 88, 99, 44],
       [ 5,  6,  7,  8]])

In [126]:
x = np.array([[4,5,6,7],[8,9,10,11]])
y = np.array([[11,12,23,44]])

In [127]:
x

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
y

array([[11, 12, 23, 44]])

In [129]:
np.concatenate((x,y))

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [11, 12, 23, 44]])

In [130]:
np.stack((x,y),axis=0)

ValueError: all input arrays must have the same shape

In [132]:
np.hstack((x,y),axis=0)

TypeError: hstack() got an unexpected keyword argument 'axis'

In [133]:
np.vstack((x,y))

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [11, 12, 23, 44]])

In [134]:
np.hstack((x,y))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [135]:
x = np.array([[4,5,6,7],[8,9,10,11]])
y = np.array([[11,12,23,44],[55,66,77,88]])

In [136]:
x

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
y

array([[11, 12, 23, 44],
       [55, 66, 77, 88]])

In [138]:
np.concatenate((x,y))

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [11, 12, 23, 44],
       [55, 66, 77, 88]])

In [139]:
np.concatenate((x,y),axis=0)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [11, 12, 23, 44],
       [55, 66, 77, 88]])

In [140]:
np.concatenate((x,y),axis=1)

array([[ 4,  5,  6,  7, 11, 12, 23, 44],
       [ 8,  9, 10, 11, 55, 66, 77, 88]])

In [141]:
np.stack((x,y))

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[11, 12, 23, 44],
        [55, 66, 77, 88]]])

In [142]:
np.hstack((x,y))

array([[ 4,  5,  6,  7, 11, 12, 23, 44],
       [ 8,  9, 10, 11, 55, 66, 77, 88]])

In [143]:
np.vstack((x,y))

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [11, 12, 23, 44],
       [55, 66, 77, 88]])

In [144]:
np.stack((x,y),axis=0)

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[11, 12, 23, 44],
        [55, 66, 77, 88]]])

In [145]:
np.stack((x,y),axis=1)

array([[[ 4,  5,  6,  7],
        [11, 12, 23, 44]],

       [[ 8,  9, 10, 11],
        [55, 66, 77, 88]]])

In [146]:
np.hstack((x,y),axis=1)

TypeError: hstack() got an unexpected keyword argument 'axis'

In [147]:
np.hstack((x,y),axis=0)

TypeError: hstack() got an unexpected keyword argument 'axis'

In [148]:
np.vstack((x,y),axis=1)

TypeError: vstack() got an unexpected keyword argument 'axis'

In [149]:
np.vstack((x,y),axis=0)

TypeError: vstack() got an unexpected keyword argument 'axis'

In [150]:
np.stack((x,y),axis=1)

array([[[ 4,  5,  6,  7],
        [11, 12, 23, 44]],

       [[ 8,  9, 10, 11],
        [55, 66, 77, 88]]])

In [151]:
np.stack((x,y),axis=2)

array([[[ 4, 11],
        [ 5, 12],
        [ 6, 23],
        [ 7, 44]],

       [[ 8, 55],
        [ 9, 66],
        [10, 77],
        [11, 88]]])

In [152]:
x

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
y

array([[11, 12, 23, 44],
       [55, 66, 77, 88]])

In [154]:
np.hstack((x,y))

array([[ 4,  5,  6,  7, 11, 12, 23, 44],
       [ 8,  9, 10, 11, 55, 66, 77, 88]])

In [155]:
np.vstack((x,y))

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [11, 12, 23, 44],
       [55, 66, 77, 88]])

In [156]:
np.dstack((x,y))

array([[[ 4, 11],
        [ 5, 12],
        [ 6, 23],
        [ 7, 44]],

       [[ 8, 55],
        [ 9, 66],
        [10, 77],
        [11, 88]]])

In [157]:
a

array([78, 88, 99, 44])

In [158]:
b

array([5, 6, 7, 8])

In [159]:
np.dstack((a,b))

array([[[78,  5],
        [88,  6],
        [99,  7],
        [44,  8]]])

In [160]:
a = np.vstack((x,y))
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [11, 12, 23, 44],
       [55, 66, 77, 88]])

In [161]:
b = np.stack((x,y),axis=1)
b

array([[[ 4,  5,  6,  7],
        [11, 12, 23, 44]],

       [[ 8,  9, 10, 11],
        [55, 66, 77, 88]]])

In [162]:
x = np.arange(8.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7.])

# DAY-5

In [5]:
import numpy as np
x=np.arange(8.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [6]:
# Spliting the array:-

np.split(x,2)

[array([0., 1., 2., 3.]), array([4., 5., 6., 7.])]

In [7]:
np.array_split(x,3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [8]:
x=np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.array_split(x,4)

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [10]:
x=np.arange(16.0).reshape(4,4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [11]:
np.hsplit(x,2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [12]:
np.vsplit(x,2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [13]:
x=np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
y=np.split(x,3)
y

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [15]:
y=np.array_split(x,3)
y

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [16]:
np.hsplit(x,2)

# because the division is not equal.

ValueError: array split does not result in an equal division

In [17]:
import numpy as np
ar=np.array([45,55,66,77,85,23])
copy=ar.copy()

In [18]:
ar

array([45, 55, 66, 77, 85, 23])

In [19]:
copy

array([45, 55, 66, 77, 85, 23])

In [20]:
id(ar)

2732697687152

In [21]:
id(copy)

2732697687344

In [22]:
import numpy as np
ar=np.array([45,55,66,77,85,23])
view=ar.view()

In [23]:
ar

array([45, 55, 66, 77, 85, 23])

In [24]:
view

array([45, 55, 66, 77, 85, 23])

In [25]:
id(ar)

2732697153392

In [26]:
id(view)

2732697683984

In [2]:
import numpy as np
ar=np.array([45,55,66,77,85,23])
copy=ar.copy()
ar[2]=59

In [3]:
ar

array([45, 55, 59, 77, 85, 23])

In [4]:
copy

array([45, 55, 66, 77, 85, 23])

In [5]:
import numpy as np
ar=np.array([45,55,66,77,85,23])
view=ar.view()
ar[3]=20

In [6]:
ar

array([45, 55, 66, 20, 85, 23])

In [7]:
view

array([45, 55, 66, 20, 85, 23])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
import numpy as np
mat=np.matrix([45,55,66,77,88])
print(mat,type(mat))

[[45 55 66 77 88]] <class 'numpy.matrix'>


In [10]:
import numpy as np
mat=np.matrix([[45,55,66,77,88]])
print(mat,type(mat))

[[45 55 66 77 88]] <class 'numpy.matrix'>


In [11]:
import numpy as np
mat=np.matrix([[[45,55,66,77,88]]])
print(mat,type(mat))

ValueError: matrix must be 2-dimensional

In [12]:
import numpy as np
import numpy.matlib
numpy.matlib.zeros((5))

matrix([[0., 0., 0., 0., 0.]])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
import numpy as np
import numpy.matlib
numpy.matlib.zeros((5,2))

matrix([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
import numpy as np
import numpy.matlib
numpy.matlib.ones((5))

matrix([[1., 1., 1., 1., 1.]])

In [16]:
import numpy as np
import numpy.matlib
numpy.matlib.ones((5,2))

matrix([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [17]:
import numpy as np
import numpy.matlib
numpy.matlib.empty((5))

matrix([[1., 1., 1., 1., 1.]])

In [18]:
import numpy as np
import numpy.matlib
numpy.matlib.empty((5,2))

matrix([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [20]:
import numpy as np
import numpy.matlib
numpy.matlib.identity((5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
import numpy as np
import numpy.matlib
numpy.matlib.identity((5,2))

TypeError: can't multiply sequence by non-int of type 'list'

In [22]:
import numpy as np
import numpy.matlib
numpy.matlib.eye((5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [24]:
import numpy as np
import numpy.matlib
numpy.matlib.eye(n=5,M=7,dtype=int)

matrix([[1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0]])

In [26]:
mat1=np.matrix([[4,5,6],[7,8,9]])
mat2=np.matrix([[8,11,12],[12,15,14]])

In [27]:
mat1

matrix([[4, 5, 6],
        [7, 8, 9]])

In [28]:
mat2

matrix([[ 8, 11, 12],
        [12, 15, 14]])

In [29]:
mat1+mat2

matrix([[12, 16, 18],
        [19, 23, 23]])

In [30]:
np.add(mat1,mat2)

matrix([[12, 16, 18],
        [19, 23, 23]])

In [31]:
mat1-mat2

matrix([[-4, -6, -6],
        [-5, -7, -5]])

In [32]:
np.subtract(mat1,mat2)

matrix([[-4, -6, -6],
        [-5, -7, -5]])

In [34]:
np.multiply(mat1,mat2)

matrix([[ 32,  55,  72],
        [ 84, 120, 126]])

In [35]:
mat1

matrix([[4, 5, 6],
        [7, 8, 9]])

In [36]:
mat2

matrix([[ 8, 11, 12],
        [12, 15, 14]])

In [37]:
np.dot(mat1,mat2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [38]:
mat1

matrix([[4, 5, 6],
        [7, 8, 9]])

In [39]:
mat2

matrix([[ 8, 11, 12],
        [12, 15, 14]])

In [41]:
mat1=mat1.T

In [42]:
mat1

matrix([[4, 7],
        [5, 8],
        [6, 9]])

In [43]:
np.dot(mat1,mat2)

matrix([[116, 149, 146],
        [136, 175, 172],
        [156, 201, 198]])

In [44]:
mat1

matrix([[4, 7],
        [5, 8],
        [6, 9]])

In [45]:
mat2

matrix([[ 8, 11, 12],
        [12, 15, 14]])

In [47]:
mat1=mat1.T

In [48]:
mat1

matrix([[4, 5, 6],
        [7, 8, 9]])

In [49]:
np.divide(mat1,mat2)

matrix([[0.5       , 0.45454545, 0.5       ],
        [0.58333333, 0.53333333, 0.64285714]])

In [50]:
np.divmod(mat1,mat2)

(matrix([[0, 0, 0],
         [0, 0, 0]]),
 matrix([[4, 5, 6],
         [7, 8, 9]]))

In [51]:
mat1

matrix([[4, 5, 6],
        [7, 8, 9]])

In [52]:
mat2

matrix([[ 8, 11, 12],
        [12, 15, 14]])

In [54]:
mat1=np.matrix([[16,5,6],[7,8,9]])
mat2=np.matrix([[8,11,12],[12,13,14]])

In [55]:
np.divmod(mat1,mat2)

(matrix([[2, 0, 0],
         [0, 0, 0]]),
 matrix([[0, 5, 6],
         [7, 8, 9]]))

In [56]:
import numpy as np
ar=np.array([[4,5,6],[6,7,8],[9,10,11]])

In [57]:
ar

array([[ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
ar[0:2,0:2]

array([[4, 5],
       [6, 7]])

In [59]:
ar[1:3,1:3]

array([[ 7,  8],
       [10, 11]])

In [60]:
ar[0:3:1,0:3:1]

array([[ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
ar[[0,1,2],[0,1,2]]

array([ 4,  7, 11])

In [62]:
ar[(0,1,2),(0,1,2)]

array([ 4,  7, 11])

In [63]:
ar

array([[ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
ar[1:3,-1:-3:-1]

array([[ 8,  7],
       [11, 10]])

In [65]:
import numpy as np
a=np.array([[45,55,66],[4,5,6]])
b=np.array([[12,13,25],[1,2,3]])

In [66]:
a

array([[45, 55, 66],
       [ 4,  5,  6]])

In [67]:
b

array([[12, 13, 25],
       [ 1,  2,  3]])

In [68]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [69]:
b.shape=(3,2)

In [70]:
a

array([[45, 55, 66],
       [ 4,  5,  6]])

In [71]:
b

array([[12, 13],
       [25,  1],
       [ 2,  3]])

In [72]:
np.dot(a,b)

array([[2047,  838],
       [ 185,   75]])

In [73]:
np.vdot(a,b)

np.int64(2937)

In [75]:
x=np.array([4,5,6,7,8])
y=np.array([1,2,3,4,5])

In [77]:
np.inner(x,y)

np.int64(100)

In [78]:
ar=np.array([[4,5],[6,7]])

In [79]:
ar

array([[4, 5],
       [6, 7]])

In [80]:
np.linalg.det(ar)

np.float64(-2.000000000000003)

In [81]:
a

array([[45, 55, 66],
       [ 4,  5,  6]])

In [82]:
b

array([[12, 13],
       [25,  1],
       [ 2,  3]])

In [83]:
np.matmul(a,b)

array([[2047,  838],
       [ 185,   75]])

In [84]:
a=[[3,2],[2,6]]
b=[4,3]

In [85]:
a=np.array([[3,2],[2,6]])
b=np.array([4,3])

In [86]:
a

array([[3, 2],
       [2, 6]])

In [87]:
b

array([4, 3])

In [88]:
np.linalg.solve(a,b)

array([1.28571429, 0.07142857])

In [89]:
np.linalg.inv(a)

array([[ 0.42857143, -0.14285714],
       [-0.14285714,  0.21428571]])

In [90]:
import numpy as np
ar=np.array([4,5,7,8,9,44,55,66])
ar

array([ 4,  5,  7,  8,  9, 44, 55, 66])

In [91]:
np.where(ar==7)

(array([2]),)

In [92]:
import numpy as np
ar=np.array([4,5,7,8,9,44,55,66,4,8,2,4,8,9])
ar

array([ 4,  5,  7,  8,  9, 44, 55, 66,  4,  8,  2,  4,  8,  9])

In [93]:
np.where(ar==4)

(array([ 0,  8, 11]),)

In [94]:
ar=np.array([[4,5,6],[7,8,9],[10,11,12]])
ar

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
np.where(ar==8)

(array([1]), array([1]))

In [96]:
ar=np.array([[4,5,6],[7,8,9],[18,11,12]])
ar

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [18, 11, 12]])

In [97]:
np.where(ar==8)

(array([1]), array([1]))

In [98]:
ar=np.array([4,5,6,7,8,9,44,55,4,88,4,69,5,4])
ar
np.where(ar%2==0)

(array([ 0,  2,  4,  6,  8,  9, 10, 13]),)

In [99]:
ar=np.array([1,2,3,4,5,6,10])
ar

array([ 1,  2,  3,  4,  5,  6, 10])

In [101]:
np.searchsorted(ar,7)

np.int64(6)

In [102]:
np.where(ar==6)

(array([5]),)

In [103]:
np.searchsorted(ar,[7,8,9])

array([6, 6, 6])

In [104]:
ar=np.array([1,2,3,4,5,6,10,11,12])
ar

array([ 1,  2,  3,  4,  5,  6, 10, 11, 12])

In [105]:
np.searchsorted(ar,[7,8,9,12,24])

array([6, 6, 6, 8, 9])

In [106]:
ar=np.array([4,5,6,7,8])

In [107]:
ar

array([4, 5, 6, 7, 8])

In [108]:
k=[True,False,True,False,False]

In [110]:
ar[k]

array([4, 6])

In [111]:
ar=np.array([12,13,4,5,6,7,8,9])
print(ar,type(ar))

[12 13  4  5  6  7  8  9] <class 'numpy.ndarray'>


In [112]:
np.random.shuffle(ar)

In [113]:
ar

array([ 5,  7,  6, 13,  8,  9,  4, 12])

In [114]:
np.random.shuffle(ar)

In [115]:
ar

array([ 8,  9,  6, 12,  5,  4,  7, 13])

In [117]:
ar=np.array([12,11,5,6,7,12,11,5,6,7,3,24,1,2,4,3,2,1])
ar

array([12, 11,  5,  6,  7, 12, 11,  5,  6,  7,  3, 24,  1,  2,  4,  3,  2,
        1])

In [119]:
np.unique(ar)

array([ 1,  2,  3,  4,  5,  6,  7, 11, 12, 24])

In [120]:
ar

array([12, 11,  5,  6,  7, 12, 11,  5,  6,  7,  3, 24,  1,  2,  4,  3,  2,
        1])

In [121]:
y=np.unique(ar)
y

array([ 1,  2,  3,  4,  5,  6,  7, 11, 12, 24])

In [123]:
y=np.unique(ar,return_index=True)
y

(array([ 1,  2,  3,  4,  5,  6,  7, 11, 12, 24]),
 array([12, 13, 10, 14,  2,  3,  4,  1,  0, 11]))

In [124]:
y=np.unique(ar,return_index=True,return_counts=True)
y

(array([ 1,  2,  3,  4,  5,  6,  7, 11, 12, 24]),
 array([12, 13, 10, 14,  2,  3,  4,  1,  0, 11]),
 array([2, 2, 2, 1, 2, 2, 2, 2, 2, 1]))

In [125]:
y=np.unique(ar)
y

array([ 1,  2,  3,  4,  5,  6,  7, 11, 12, 24])

In [126]:
np.resize(y,(4,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7, 11]])

In [127]:
y

array([ 1,  2,  3,  4,  5,  6,  7, 11, 12, 24])

In [128]:
y=np.resize(y,(4,2))
y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7, 11]])

In [129]:
y.resize(4,2)

In [130]:
y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7, 11]])

In [131]:
y.flatten()

array([ 1,  2,  3,  4,  5,  6,  7, 11])

In [132]:
y.flatten(order="C")

array([ 1,  2,  3,  4,  5,  6,  7, 11])

In [133]:
y.flatten(order="F")

array([ 1,  3,  5,  7,  2,  4,  6, 11])

In [134]:
y.flatten(order="a")

array([ 1,  2,  3,  4,  5,  6,  7, 11])

In [135]:
y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7, 11]])

In [136]:
np.ravel(y)

array([ 1,  2,  3,  4,  5,  6,  7, 11])

In [137]:
y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7, 11]])

In [138]:
np.ravel(y,order="C")

array([ 1,  2,  3,  4,  5,  6,  7, 11])

In [139]:
np.ravel(y,order="F")

array([ 1,  3,  5,  7,  2,  4,  6, 11])

In [140]:
np.ravel(y,order="k")

array([ 1,  2,  3,  4,  5,  6,  7, 11])

In [141]:
np.ravel(y,order="a")

array([ 1,  2,  3,  4,  5,  6,  7, 11])

In [142]:
ar=np.array([4,5,6,7,11])
print(ar,type(ar))

[ 4  5  6  7 11] <class 'numpy.ndarray'>


In [143]:
np.searchsorted(ar,8)

np.int64(4)

In [144]:
np.insert(ar,4,8)

array([ 4,  5,  6,  7,  8, 11])

In [145]:
ar

array([ 4,  5,  6,  7, 11])

In [146]:
np.insert(ar,(2,4),8)

array([ 4,  5,  8,  6,  7,  8, 11])

In [147]:
np.insert(ar,3,[6,7,8])

array([ 4,  5,  6,  6,  7,  8,  7, 11])

In [148]:
ar

array([ 4,  5,  6,  7, 11])

In [149]:
np.insert(ar,(2,3),[7,8])

array([ 4,  5,  7,  6,  8,  7, 11])

In [150]:
np.insert(ar,(2,3),[8,9,10])

ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)

In [151]:
np.insert(ar,(2),[8,9,10])

array([ 4,  5,  8,  9, 10,  6,  7, 11])

In [152]:
ar1=np.array([[4,5,6],[7,8,9]])
ar1

array([[4, 5, 6],
       [7, 8, 9]])

In [154]:
np.insert(ar1,2,2,axis=0)

array([[4, 5, 6],
       [7, 8, 9],
       [2, 2, 2]])

In [156]:
np.insert(ar1,1,3,axis=1)

array([[4, 3, 5, 6],
       [7, 3, 8, 9]])

In [157]:
np.insert(ar1,2,[1,2,3],axis=0)

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [158]:
np.insert(ar1,2,[1,2],axis=0)

ValueError: could not broadcast input array from shape (1,2) into shape (1,3)

In [159]:
np.insert(ar1,2,[1,2],axis=1)

array([[4, 5, 1, 6],
       [7, 8, 2, 9]])

In [160]:
ar

array([ 4,  5,  6,  7, 11])

In [161]:
np.append(ar,88)

array([ 4,  5,  6,  7, 11, 88])

In [162]:
ar

array([ 4,  5,  6,  7, 11])

In [163]:
np.append(ar,[88,99,100])

array([  4,   5,   6,   7,  11,  88,  99, 100])

In [164]:
ar1

array([[4, 5, 6],
       [7, 8, 9]])

In [165]:
np.append(ar1,[[2,3,6]],0)

array([[4, 5, 6],
       [7, 8, 9],
       [2, 3, 6]])

In [167]:
np.append(ar1,[[2,3,6],[6,7,8]],1)

array([[4, 5, 6, 2, 3, 6],
       [7, 8, 9, 6, 7, 8]])

In [168]:
ar1

array([[4, 5, 6],
       [7, 8, 9]])

In [169]:
ar1

array([[4, 5, 6],
       [7, 8, 9]])

In [170]:
np.insert(ar1,2,[1,2],axis=1)

array([[4, 5, 1, 6],
       [7, 8, 2, 9]])

In [171]:
ar

array([ 4,  5,  6,  7, 11])

In [172]:
ar1

array([[4, 5, 6],
       [7, 8, 9]])

# DAY-6

In [175]:
import numpy as np

In [176]:
ar1

array([[4, 5, 6],
       [7, 8, 9]])

In [177]:
np.insert(ar1,2,[1,2],axis=1)

array([[4, 5, 1, 6],
       [7, 8, 2, 9]])

In [178]:
ar

array([ 4,  5,  6,  7, 11])

In [179]:
ar1

array([[4, 5, 6],
       [7, 8, 9]])

In [180]:
np.delete(ar,2)

array([ 4,  5,  7, 11])

In [181]:
ar

array([ 4,  5,  6,  7, 11])

In [182]:
np.delete(ar1,2)

array([4, 5, 7, 8, 9])

In [183]:
np.delete(ar1,2,axis=1)

array([[4, 5],
       [7, 8]])

In [184]:
ar1

array([[4, 5, 6],
       [7, 8, 9]])

In [185]:
np.delete(ar1,1,axis=0)

array([[4, 5, 6]])

In [186]:
ar1

array([[4, 5, 6],
       [7, 8, 9]])

In [187]:
np.transpose(ar1)

array([[4, 7],
       [5, 8],
       [6, 9]])

In [188]:
ar1.T

array([[4, 7],
       [5, 8],
       [6, 9]])

In [189]:
np.swapaxes(ar1,1,0)

array([[4, 7],
       [5, 8],
       [6, 9]])